services:
  user:
    build: './UserService'
    depends_on:
      - user-db  
    expose: 
      - 8080  

  user-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Learning1234 
      - MSSQL_PID=Evaluation
    expose:
      - 1433
  
  nginx:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user

